### ISSUE TITLE
Investigate how we can remove more windows related crates when vendoring

### ISSUE THREAD

**Issue by 7flying** [fdo-rs/fido-device-onboard-rs#514]
See discussion at #513 , we do have still some windows crates that we ship when vendoring, but we might be able to remove them.

If we can't, we should consider opening issues on other projects so that the windows target becomes optional.

**Comment by mmartinv** [comment]
I found [cargo-vendor-filterer](https://github.com/coreos/cargo-vendor-filterer) command by chance and it looks like it does exactly what we want:
```console
cargo install cargo-vendor-filterer
rm -rf vendor
cargo vendor-filterer --platform='*-unknown-linux-gnu'
```
