### ISSUE TITLE
`fdo-rs / fido-device-onboard-rs` not allowed to run Packit CI 

### ISSUE THREAD

**Issue by 7flying** [fdo-rs/fido-device-onboard-rs#560]
After the repo migration we have to update some permissions in Packit, as it is now the RPM builds are not allowed to run.

See [this warning](https://github.com/fdo-rs/fido-device-onboard-rs/pull/559/checks?check_run_id=17729264980) for instance:

```
Packit-as-a-Service / rpm-build:centos-stream-9-aarch64
github.com/fdo-rs/fido-device-onboard-rs.git not allowed!
```

**Comment by miabbott** [comment]
It looks like we need @nullr0ute to respond to this packit issue - https://github.com/packit/notifications/issues/569

**Comment by nullr0ute** [comment]
Yep, I saw the email, I mentioned this with @7flying when we were talking earlier today but I've not had time to get to it yet

**Comment by nullr0ute** [comment]
This should now be fixed
