### ISSUE TITLE
Automatic merge-queue / mergify not working anymore

### ISSUE THREAD

**Issue by 7flying** [fdo-rs/fido-device-onboard-rs#571]
After a PR is reviewed and approved mergify used to take care of the merge automatically, but it no longer does, and it shows the following warning:

>Branch protection settings are not validated anymore
> [Branch protection](https://docs.github.com/en/github/administering-a-repository/about-protected-branches) is enabled and is preventing Mergify to merge the pull request. Mergify will merge when branch protection settings validate the pull request once again. (detail: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.)

it looks like we should disable branch protection.

**Comment by 7flying** [comment]
See https://github.com/fdo-rs/fido-device-onboard-rs/pull/570 as an example

**Comment by nullr0ute** [comment]
> it looks like we should disable branch protection.

Entirely possible, I think that's enabled by default, go for it.

**Comment by 7flying** [comment]
Merfigy needed to be given push access, I haven't modified the branch protection rules, so all good :+1:
