### ISSUE TITLE
Bump libcryptsetup-rs support to 0.9

### ISSUE THREAD

**Issue by nullr0ute** [fdo-rs/fido-device-onboard-rs#588]
We bumped the devicemapper rev up but not libcryptsetup-rs to 0.9 and I believe they're connected. Review any possible API changes needed and bump the version to 0.9

**Comment by 7flying** [comment]
I've bumped libcryptsetup-rs in #582, that seems to enable the RPM build in Fedora 39, we are just blocked by the openssl package.

**Comment by 7flying** [comment]
Bumped with #598
