### ISSUE TITLE
Implement the Conformance Service Info

### ISSUE THREAD

**Issue by mmartinv** [fdo-rs/fido-device-onboard-rs#619]
To be able to pass the FIDO Alliance Conformance Tests the Onboarding Server must implement the [Conformance Service Info](https://github.com/fido-alliance/conformance-test-tools-resources/blob/main/docs/FDO/Pre-Interop/README.md) to provide the Device with the required token used to notify the successful onboarding to the [Dasboard API](https://github.com/fido-alliance/conformance-test-tools-resources/blob/main/docs/FDO/Pre-Interop/Dashboard-API.md) as described in the [Step by Step](https://github.com/fido-alliance/conformance-test-tools-resources/blob/main/docs/FDO/Pre-Interop/Step-by-step.md) documentation.

**Comment by 7flying** [comment]
Closing this one in favour of https://github.com/fdo-rs/fido-device-onboard-rs/issues/624 because I've seen it sync-ed  downstream first
