### ISSUE TITLE
no fdo-manufacturing-client in edge device

### ISSUE THREAD

**Issue by henrywang** [fdo-rs/fido-device-onboard-rs#645]
For the postgres test, I need to run `fdo-manufacturing-client no-plain-di --insecure --manufacturing-server-url` to generate a new OV in `manufacturer_vouchers` table.
But for the installed Edge system, I can't find `fdo-manufacturing-client`. It should be installed by `fdo-init` which is only run in coreos-installer part.

**Comment by runcom** [comment]
@henrywang can you include `fdo-init` in the system? it's just an rpm so you should be able to install, then run `fdo-manufacturing-client`?

**Comment by henrywang** [comment]
> @henrywang can you include `fdo-init` in the system? it's just an rpm so you should be able to install, then run `fdo-manufacturing-client`? (this is still a test, so no biggie)

This is not a problem any more. The https://github.com/fdo-rs/fido-device-onboard-rs/blob/657fefbc641ab588fd52bdcb630a2b236fd7d66d/dracut/52fdo/manufacturing-client-service#L5 can register to manufacturing server and generate OV.
So we can close this issue.
