### ISSUE TITLE
Enhance CI to perform end-to-end tests based on RPM-built code

### ISSUE THREAD

**Issue by miabbott** [fdo-rs/fido-device-onboard-rs#646]
Based on the errors reported in #644 and #645, we need better coverage in our CI tests that test a more complete end-to-end solution.

This should include running a client on a system with SELinux enabled and the packaged FDO bits installed as a customer would have them installed.

We also need to test both the sqlite and Postgres paths

**Comment by 7flying** [comment]
- we should build and install the RPMs to catch all the issues that any client may face
- gitlab for runners to use VMs (maybe?)
- reuse our existing CI whenever it is possible
- for the postgres test we could reuse existing scripts from <https://github.com/fdo-rs/fido-device-onboard-rs/blob/main/test/fdo-postgres.sh>

**Comment by 7flying** [comment]
- enable c9s builds in copr for FDO

**Comment by henrywang** [comment]
I think the Testing farm + TMT would be the best choice to drive the test.
