### ISSUE TITLE
Dependabot is failing to set the reviewers.

### ISSUE THREAD

**Issue by mmartinv** [fdo-rs/fido-device-onboard-rs#698]
Dependabot tried to add @fdo-rs/fdo-rs-maintainers as a reviewer to this PR, but received the following error from GitHub:
```
POST https://api.github.com/repos/fdo-rs/fido-device-onboard-rs/pulls/691/requested_reviewers: 422 - Reviews may only be requested from collaborators. One or more of the teams you specified is not a collaborator of the fdo-rs/fido-device-onboard-rs repository. // See: https://docs.github.com/rest/pulls/review-requests#request-reviewers-for-a-pull-request
```

Maybe the `fdo-rs-maintainers` group has been renamed to `fdo-rs-team`?

**Comment by nullr0ute** [comment]
I don't think we could take the groups over when we migrated to the fdo-rs org and naming was revisited, I suspect you're basically correct, the team is fdo-team (no rs)
